name: Build distributions and container images
on: push
jobs:
  build_distribution:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle', '**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Cache Ghidra dependency repository
        uses: actions/cache@v2
        with:
          path: ghidra/upstream/flatRepo
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/fetchDependencies.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Install dependencies ${{ matrix.os }}
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install -y winflexbison
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Download Ghidra dependency repository
        working-directory: ghidra/upstream
        run: |
          gradle --init-script gradle/support/fetchDependencies.gradle init --quiet 2>&1 > ghidra-dependencies.log
        env:
          GRADLE_OPTS:  -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.daemon=false

      - name: Build Ghidra
        working-directory: ghidra/upstream
        run: |
          gradle buildGhidra
        env:
          GRADLE_OPTS:  -Dorg.gradle.parallel=true -Dorg.gradle.caching=true -Dorg.gradle.daemon=false

      - name: Archive distribution
        uses: actions/upload-artifact@v2
        with:
          name: ghidra-distribution
          path: ghidra/upstream/build/dist/